version: '3.8'

services:
  redis:
    image: "redis:7.2-alpine"
    volumes:
      - "redis:/data"
  migration:
    build: .
    depends_on:
      - db
    command: python manage.py migrate --noinput
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env.prod
  web:
    build: .
    depends_on:
      - db
    command: gunicorn paList.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/

    env_file:
      - ./.env.prod
  beat:
    build: .
    depends_on:
      - redis
      - db
      - migration
    command: python -m celery -A paList  beat
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env.prod
  worker:
    build: .
    depends_on:
      - redis
      - db
      - migration
    command: python -m celery -A paList  worker
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env.prod
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - web
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db.prod

volumes:
  postgres_data:
  redis: {}