# Generated by Django 4.1.2 on 2022-10-26 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edl', '0002_alter_edl_edl_type_edlentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edlentry',
            name='edl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='edl.edl'),
        ),
    ]
