# Generated by Django 4.1.2 on 2023-04-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edl', '0003_alter_edlentry_edl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edl',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
