# Generated by Django 4.1.2 on 2024-01-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edl', '0004_alter_edl_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.CharField(max_length=50)),
                ('edl_name', models.CharField(max_length=50)),
                ('edl_entry', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=20)),
                ('log_message', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'External Dynamic List Log',
                'verbose_name_plural': 'External Dynamic Logs',
            },
        ),
        migrations.AlterModelOptions(
            name='edl',
            options={'verbose_name': 'External Dynamic List', 'verbose_name_plural': 'External Dynamic Lists'},
        ),
        migrations.AlterModelOptions(
            name='edlentry',
            options={'verbose_name': 'External Dynamic List Entry', 'verbose_name_plural': 'External Dynamic Entries'},
        ),
        migrations.AlterField(
            model_name='edl',
            name='edl_type',
            field=models.CharField(choices=[('url', 'URL'), ('fqdn', 'FQDN'), ('ip_address', 'IP Address')], max_length=20),
        ),
    ]
