# Generated by Django 4.1.2 on 2024-01-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edl', '0006_alter_edllog_edl_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edllog',
            name='log_message',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
